# Generated by Django 5.1.7 on 2025-03-16 21:48

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('pays', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.CharField(max_length=255)),
                ('date_publication', models.DateTimeField(verbose_name='Date de publication')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('auteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.auteur')),
            ],
        ),
    ]
